platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/autolink-ios'

target 'mobile' do
  config = use_native_modules!
  pod 'LibTorch-Lite'
  pod 'LibTorch-Lite-TorchVision'
end

