platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/autolink-ios'

target 'PestAI' do
  config = use_native_modules!
  use_frameworks!
  pod 'LibTorch-Lite'
  pod 'LibTorch-Lite-TorchVision'
  use_react_native!(:path => config["reactNativePath"])
end
